# This is the config file used in a test
database:
  provider: "postgres"
  host: "localhost"
  port: 5432
  database: "go_dbmap"
  user: "go_dbmap"
  password: "go_dbmap"

output:
  path: "output"
  suffix: "_db"
  lang: "go"

proto:
  path: "output/proto"
  java_package: "com.example"
  version: "proto2"

generator:
  schemas: ["public", "test_schema"]
  excluded_tables: ["foo", "bar"]
  excluded_columns:
    -
      table: "test_schema.user"
      columns: ["pword_hash", "geog"]
    -
      table: "foo"
      columns: ["bar"]
  indexed_lookups: true
  mapping:
    -
      table: "test_schema.user"
      queries:
        -
          name: "get_pword_hash"
          query: "SELECT pword_hash FROM test_schema.user WHERE email = $1"
        -
          name: "update_pword_hash"
          query: "UPDATE test_schema.user SET pword_hash = $2 WHERE email = $1"
    -
      table: "part"
      queries:
        -
          name: "get_product"
          query: "SELECT p1.* FROM product p1, product_parts pp, part p WHERE p1.product_id = pp.product_id AND pp.part_id = p.part_id AND p.part_name = $1"
  transforms:
    -
      table: "test_schema.user"
      xforms:
        # For the select transform, we need to know the datatype of the product of the transform. This is needed for
        # generating the protobufs
        select:
          -
            column: "lat"
            data_type: "decimal"
            xform: "ST_Y(geog::geometry)"
          -
            column: "lon"
            data_type: "decimal"
            xform: "ST_X(geog::geometry)"
        insert:
          -
            column: "geog"
            data_type: "geography"
            xform: "ST_POINT($lat, $lon)::geography"
        update:
          -
            column: "geog"
            data_type: "geography"
            xform: "ST_POINT($lat, $lon)::geography"
    -
      table: "public.foo"
      xforms:
        select:
          -
            column: "foobar"
            data_type: "integer"
            xform: "1"