// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_schema/foo.proto

package test_schema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Foo struct {
	Bar                  *string  `protobuf:"bytes,1,opt,name=bar" json:"bar,omitempty"`
	Baz                  *string  `protobuf:"bytes,2,opt,name=baz" json:"baz,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b63c4d2fbc5c3cd6, []int{0}
}

func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (m *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(m, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetBar() string {
	if m != nil && m.Bar != nil {
		return *m.Bar
	}
	return ""
}

func (m *Foo) GetBaz() string {
	if m != nil && m.Baz != nil {
		return *m.Baz
	}
	return ""
}

func init() {
	proto.RegisterType((*Foo)(nil), "test_schema.Foo")
}

func init() { proto.RegisterFile("test_schema/foo.proto", fileDescriptor_b63c4d2fbc5c3cd6) }

var fileDescriptor_b63c4d2fbc5c3cd6 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x49, 0x2d, 0x2e,
	0x89, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0xd4, 0x4f, 0xcb, 0xcf, 0xd7, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x46, 0x12, 0x56, 0xd2, 0xe4, 0x62, 0x76, 0xcb, 0xcf, 0x17, 0x12, 0xe0, 0x62,
	0x4e, 0x4a, 0x2c, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x21, 0x22, 0x55, 0x12,
	0x4c, 0x30, 0x91, 0x2a, 0x27, 0x3d, 0x2e, 0xf1, 0xe4, 0xfc, 0x5c, 0xbd, 0xd4, 0x8a, 0xc4, 0xdc,
	0x82, 0x9c, 0x54, 0x3d, 0x24, 0x53, 0x9c, 0x38, 0x80, 0x66, 0x04, 0x80, 0x0c, 0x0f, 0x60, 0xfc,
	0xc1, 0xc8, 0xb8, 0x88, 0x89, 0xd9, 0xd5, 0xc5, 0x17, 0x10, 0x00, 0x00, 0xff, 0xff, 0x72, 0x55,
	0x74, 0x79, 0x7f, 0x00, 0x00, 0x00,
}
